# Generated by Django 6.0.4 on 2026-07-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
