# Generated by Django 6.0.4 on 2026-07-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobengagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
