# Generated by Django 6.0.4 on 2026-07-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='match_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
