# Generated by Django 6.0.4 on 2026-07-15 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_application_match_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('REVIEWED', 'Reviewed'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW', 'Interview Scheduled'), ('OFFER', 'Offer Extended'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='SavedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_candidates', to=settings.AUTH_USER_MODEL)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_employers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('employer', 'seeker')},
            },
        ),
    ]
