# Generated by Django 6.0.4 on 2026-07-15 17:29

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_application_status_alter_job_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=django_countries.fields.CountryField(blank=True, db_index=True, max_length=2),
        ),
    ]
