# Generated by Django 6.0.4 on 2026-07-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_jobcategory_historicaljob_category_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljob',
            name='anywhere_in_bd',
            field=models.BooleanField(default=False, verbose_name='Anywhere in Bangladesh'),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='is_salary_negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='professional_qualifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='show_salary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='sub_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='anywhere_in_bd',
            field=models.BooleanField(default=False, verbose_name='Anywhere in Bangladesh'),
        ),
        migrations.AddField(
            model_name='job',
            name='is_salary_negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='professional_qualifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='show_salary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='sub_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='education',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='employment_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contractual'), ('INTERNSHIP', 'Internship')], db_index=True, default='FULL_TIME', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='education',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contractual'), ('INTERNSHIP', 'Internship')], db_index=True, default='FULL_TIME', max_length=20),
        ),
    ]
