# Generated by Django 6.0.4 on 2026-08-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_historicaljob_anywhere_in_bd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljob',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)'), ('INR', 'Indian Rupee (₹)'), ('BDT', 'Bangladeshi Taka (৳)')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='job',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)'), ('INR', 'Indian Rupee (₹)'), ('BDT', 'Bangladeshi Taka (৳)')], default='USD', max_length=3),
        ),
    ]
