# Generated by Django 6.0.4 on 2026-08-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_alter_historicaljob_currency_alter_job_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljob',
            name='external_apply_url',
            field=models.URLField(blank=True, help_text='If provided, applicants will be redirected to this URL when clicking Apply', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='external_apply_url',
            field=models.URLField(blank=True, help_text='If provided, applicants will be redirected to this URL when clicking Apply', null=True),
        ),
    ]
