# Generated by Django 6.0.4 on 2026-07-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Jobbee', max_length=100)),
                ('primary_color', models.CharField(default='#000000', help_text='Hex color code for primary color', max_length=7)),
                ('secondary_color', models.CharField(default='#ffffff', help_text='Hex color code for secondary color', max_length=7)),
                ('accent_color', models.CharField(default='#3b82f6', help_text='Hex color code for accent color (links, active states)', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
