# Generated by Django 6.0.4 on 2026-07-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Platform v2.0 is Live', help_text='Small text badge at the top', max_length=100)),
                ('heading_line_1', models.CharField(default='Ship your', help_text='First line of the main heading', max_length=100)),
                ('heading_line_2_colored', models.CharField(default='career.', help_text='Second colored line of the main heading', max_length=100)),
                ('subheading', models.TextField(default='The ultra-fast, premium hiring infrastructure designed for top-tier engineers, designers, and innovators.')),
                ('search_placeholder_1', models.CharField(default='Search roles, skills or companies', max_length=100)),
                ('search_placeholder_2', models.CharField(default='Location or Remote', max_length=100)),
                ('search_button_text', models.CharField(default='Find Roles', max_length=50)),
                ('popular_tags', models.CharField(default='Remote, Design, Backend, Marketing, Data', help_text='Comma-separated popular search tags', max_length=255)),
                ('card_1_number', models.CharField(default='10k+', help_text='e.g. 10k+', max_length=20)),
                ('card_1_label', models.CharField(default='Active Jobs', help_text='e.g. Active Jobs', max_length=50)),
                ('card_2_title', models.CharField(default='UX Designer', help_text='e.g. UX Designer', max_length=50)),
                ('card_2_tag_1', models.CharField(default='FULL TIME', max_length=20)),
                ('card_2_tag_2', models.CharField(default='REMOTE', max_length=20)),
                ('card_3_number', models.CharField(default='5k+', max_length=20)),
                ('card_3_label', models.CharField(default='Employers', max_length=50)),
                ('card_4_number', models.CharField(default='24h', max_length=20)),
                ('card_4_label', models.CharField(default='Avg. Response', max_length=50)),
            ],
            options={
                'verbose_name': 'Hero Section Settings',
                'verbose_name_plural': 'Hero Section Settings',
            },
        ),
    ]
