# Generated by Django 6.0.4 on 2026-07-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(help_text='Upload a company logo', upload_to='trusted_companies/')),
                ('order', models.IntegerField(default=0, help_text='Order in which it appears')),
            ],
            options={
                'verbose_name': 'Trusted Company',
                'verbose_name_plural': 'Trusted Companies',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='herosectionsettings',
            name='companies_section_title',
            field=models.CharField(default='Trusted by innovative companies', help_text='Title above the trusted company logos', max_length=100),
        ),
    ]
