# Generated by Django 6.0.4 on 2026-07-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_trustedcompany_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosectionsettings',
            name='stats_1_label',
            field=models.CharField(default='Active Jobs', max_length=50),
        ),
        migrations.AddField(
            model_name='herosectionsettings',
            name='stats_1_number',
            field=models.CharField(default='10k+', max_length=20),
        ),
        migrations.AddField(
            model_name='herosectionsettings',
            name='stats_2_label',
            field=models.CharField(default='Employers', max_length=50),
        ),
        migrations.AddField(
            model_name='herosectionsettings',
            name='stats_2_number',
            field=models.CharField(default='5k+', max_length=20),
        ),
        migrations.AddField(
            model_name='herosectionsettings',
            name='stats_3_label',
            field=models.CharField(default='Avg. Response Time', max_length=50),
        ),
        migrations.AddField(
            model_name='herosectionsettings',
            name='stats_3_number',
            field=models.CharField(default='24h', max_length=20),
        ),
    ]
