# Generated by Django 6.0.4 on 2026-07-19 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_herosectionsettings_stats_1_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosectionsettings',
            name='stats_1_label',
        ),
        migrations.RemoveField(
            model_name='herosectionsettings',
            name='stats_1_number',
        ),
        migrations.RemoveField(
            model_name='herosectionsettings',
            name='stats_2_label',
        ),
        migrations.RemoveField(
            model_name='herosectionsettings',
            name='stats_2_number',
        ),
        migrations.RemoveField(
            model_name='herosectionsettings',
            name='stats_3_label',
        ),
        migrations.RemoveField(
            model_name='herosectionsettings',
            name='stats_3_number',
        ),
    ]
