# Generated by Django 6.0.4 on 2026-07-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_herosectionsettings_stats_1_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(default='USD', help_text='e.g. USD', max_length=10)),
                ('base_currency_symbol', models.CharField(default='$', help_text='e.g. $', max_length=5)),
                ('display_currency', models.CharField(default='BDT', help_text='e.g. BDT', max_length=10)),
                ('display_currency_symbol', models.CharField(default='৳', help_text='e.g. ৳', max_length=5)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=120.0, help_text='1 Base = X Display', max_digits=10)),
                ('enable_conversion', models.BooleanField(default=True, help_text='Turn currency conversion on or off globally')),
            ],
            options={
                'verbose_name': 'Currency Settings',
                'verbose_name_plural': 'Currency Settings',
            },
        ),
    ]
