# Generated by Django 6.0.4 on 2026-07-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_currencysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(help_text='The testimonial text')),
                ('author_name', models.CharField(max_length=100)),
                ('author_title', models.CharField(help_text='e.g. Product Designer at Airbnb', max_length=100)),
                ('author_avatar', models.ImageField(blank=True, help_text='Upload an avatar. If empty, a generated avatar will be used.', null=True, upload_to='testimonials/')),
                ('badge_initial', models.CharField(default='a', help_text="Initial for the hired badge (e.g. 'a')", max_length=5)),
                ('hired_role', models.CharField(default='Product Designer', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Show this testimonial on the homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
    ]
