# Generated by Django 6.0.4 on 2026-08-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencysettings',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='1 Base = X Display', max_digits=10),
        ),
    ]
