# Generated by Django 6.0.4 on 2026-08-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_newslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(help_text='e.g. USD, EUR, GBP', max_length=3, unique=True)),
                ('rate_to_base', models.DecimalField(decimal_places=4, help_text='How much of this currency equals 1 Base Currency', max_digits=10)),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
            },
        ),
    ]
