# Generated by Django 6.0.4 on 2026-08-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_exchangerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencysettings',
            name='base_currency',
            field=models.CharField(default='BDT', help_text='e.g. BDT', max_length=10),
        ),
        migrations.AlterField(
            model_name='currencysettings',
            name='base_currency_symbol',
            field=models.CharField(default='৳', help_text='e.g. ৳', max_length=5),
        ),
        migrations.AlterField(
            model_name='currencysettings',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='1 Base = X Display', max_digits=10),
        ),
    ]
