# Generated by Django 6.0.4 on 2026-07-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_companyphoto_companyreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='age_group',
            field=models.CharField(blank=True, choices=[('18-24', '18-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45-54', '45-54'), ('55+', '55+')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1, null=True),
        ),
    ]
