# Generated by Django 6.0.4 on 2026-07-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_seekerprofile_age_group_seekerprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='company_banner',
            field=models.ImageField(blank=True, null=True, upload_to='company_banners/'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
