# Generated by Django 6.0.4 on 2026-07-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_employerprofile_company_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='missing_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='resume_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='resume_suggestions',
            field=models.TextField(blank=True),
        ),
    ]
