# Generated by Django 6.0.4 on 2026-07-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_employerprofile_credits_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
