# Generated by Django 6.0.4 on 2026-07-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_employerprofile_company_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='verification_docs/'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='verification_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20),
        ),
    ]
