# Generated by Django 6.0.4 on 2026-07-15 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_employerprofile_verification_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_seats', to='accounts.employerprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_seat_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
