# Generated by Django 6.0.4 on 2026-07-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_recruiterseat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerprofile',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='skills',
            field=models.CharField(blank=True, db_index=True, help_text='Comma-separated skills', max_length=255),
        ),
    ]
