# Generated by Django 6.0.4 on 2026-07-15 17:29

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_seekerprofile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerprofile',
            name='location',
            field=django_countries.fields.CountryField(blank=True, db_index=True, max_length=2),
        ),
    ]
