# Generated by Django 6.0.4 on 2026-07-28 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_historicalemployerprofile_historicalseekerprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalseekerprofile',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='seekerprofile',
            name='resume',
        ),
        migrations.AddField(
            model_name='historicalseekerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalseekerprofile',
            name='career_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalseekerprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='historicalseekerprofile',
            name='github_url',
            field=models.URLField(blank=True, null=True, verbose_name='GitHub URL'),
        ),
        migrations.AddField(
            model_name='historicalseekerprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='historicalseekerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='historicalseekerprofile',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='Other Social Media URL'),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='career_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='github_url',
            field=models.URLField(blank=True, null=True, verbose_name='GitHub URL'),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='Other Social Media URL'),
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('relationship', models.CharField(help_text='e.g. Former Manager, Colleague', max_length=100)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('contact_info', models.CharField(help_text='Email or phone number', max_length=255)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='accounts.seekerprofile')),
            ],
        ),
    ]
