# Generated by Django 6.0.4 on 2026-07-28 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_historicalseekerprofile_resume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='0.00 means free', max_digits=10)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='resume_templates/thumbnails/')),
                ('html_template', models.CharField(help_text='Path to the HTML file (e.g. accounts/resume_templates/free.html)', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='historicalseekerprofile',
            name='active_resume_template',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.resumetemplate'),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='active_resume_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_profiles', to='accounts.resumetemplate'),
        ),
        migrations.CreateModel(
            name='PurchasedTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('stripe_session_id', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_templates', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.resumetemplate')),
            ],
            options={
                'unique_together': {('user', 'template')},
            },
        ),
    ]
