# Generated by Django 6.0.4 on 2026-07-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_historicalseekerprofile_wallet_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalseekerprofile',
            name='profile_picture',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='seeker_pictures/'),
        ),
    ]
