# Generated by Django 6.0.4 on 2026-07-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_historicalseekerprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalseekerprofile',
            name='extracurricular_activities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalseekerprofile',
            name='languages',
            field=models.CharField(blank=True, help_text='Comma-separated languages', max_length=255),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='extracurricular_activities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='languages',
            field=models.CharField(blank=True, help_text='Comma-separated languages', max_length=255),
        ),
    ]
