# Generated by Django 6.0.4 on 2026-07-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_historicalseekerprofile_extracurricular_activities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='company_document',
            field=models.FileField(blank=True, null=True, upload_to='company_docs/'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployerprofile',
            name='company_document',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployerprofile',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployerprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployerprofile',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
