# Generated by Django 6.0.4 on 2026-07-28 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_employerprofile_company_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='grade_value',
            field=models.CharField(blank=True, help_text='e.g. 3.85, A+, 1st Division', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='grading_system',
            field=models.CharField(blank=True, choices=[('CGPA', 'CGPA'), ('GPA', 'GPA'), ('GRADE', 'Grade'), ('DIVISION', 'Division')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalseekerprofile',
            name='alternative_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Alternative Phone Number'),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='alternative_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Alternative Phone Number'),
        ),
        migrations.CreateModel(
            name='EmployerFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='accounts.employerprofile')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='accounts.seekerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('employer', 'seeker')},
            },
        ),
    ]
