# Generated by Django 6.0.4 on 2026-07-30 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_education_grade_value_education_grading_system_and_more'),
        ('jobs', '0015_historicaljob_anywhere_in_bd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalseekerprofile',
            name='job_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='jobs.jobcategory'),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='job_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seekers', to='jobs.jobcategory'),
        ),
    ]
