# Generated by Django 6.0.4 on 2026-07-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='job_limit',
            field=models.IntegerField(default=1, help_text='Number of jobs allowed (-1 for unlimited)'),
        ),
    ]
