# Generated by Django 6.0.4 on 2026-07-15 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_employerprofile_company_banner_and_more'),
        ('subscriptions', '0002_alter_plan_job_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('addon_type', models.CharField(help_text='e.g., FEATURED_JOB, EXTRA_JOB', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmployerAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.addon')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='accounts.employerprofile')),
            ],
        ),
    ]
