# Generated by Django 6.0.4 on 2026-07-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_addon_employeraddon'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='has_advanced_matching',
            field=models.BooleanField(default=False),
        ),
    ]
