# Generated by Django 6.0.4 on 2026-07-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_employersubscription_jobs_posted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='analytics_dashboard',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='applications_text',
            field=models.CharField(blank=True, default='Unlimited', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='best_for',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='company_branding',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='custom_hiring_campaigns',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='cv_database_access',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='dedicated_account_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='detail',
            field=models.CharField(blank=True, help_text='Short description of the plan', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='featured_jobs_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='homepage_placement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='job_posts_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='priority_customer_support',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='recruitment_consultation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='remote_hybrid_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='social_media_promotion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
