# Generated by Django 6.0.4 on 2026-08-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_coupon_couponusage_historicalcoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency code for the price (USD, BDT, etc.)', max_length=3),
        ),
    ]
